### ISSUE TITLE
PDF documents are not handled by the proper viewer (Android 12)

### ISSUE THREAD

**Issue by sebiIO** [EffnerApp/EffnerApp#163]
When I open a PDF through the app (e. g. the privacy policy), the request is handled by the webbrowser instead of the Google PDF viewer. I think this is an issue related to android 12 as I remember it used to work with previous android versions.

![Screenshot_20211119-184204](https://user-images.githubusercontent.com/52716424/142667628-87daa332-8dda-4aa8-8db4-ee8fd36dba1d.png)
![Screenshot_20211119-184207](https://user-images.githubusercontent.com/52716424/142667634-6d502e68-b307-48c3-8a1a-459a25c3c907.png)

**Comment by Luuuuuis** [comment]
Same issue on android11

**Comment by sebiIO** [comment]
Apparently the view handler is determined by the file extension of the URL, so our short links like https://go.effner.app/privacy wouldn't work. But other documents like the exams or timetable plans have a .pdf file extension, however these aren't working on android 12 either. Could you check it for android 11, please?

**Comment by Luuuuuis** [comment]
Can confirm

**Comment by sebiIO** [comment]
It will be fixed in the next version (see: EffnerApp/effnerapp-next@78b4272adb105d987c2709e298d8cc2252c40370)
