### ISSUE TITLE
DSBmobile returning incomplete timetable meta data

### ISSUE THREAD

**Issue by clyaIO** [EffnerApp/EffnerApp#18]
Sometimes the dsbmobile light api returns an incomplete set of data (Missing `child` object in the `Childs` array, where the uri (`Detail`) of the timetable is normally located):
```json
[
  {
    "Childs": [],
    "ConType": 2,
    "Date": "30.03.2022 08:28",
    "Detail": "",
    "Id": "someUUID",
    "Index": 0,
    "Preview": "",
    "Prio": 0,
    "Tags": "",
    "Title": "Vetretungen_mobil - esis",
  },
]
```

The meta data should look like this:
```json
[
  {
    "Childs": [
      {
        "Childs": [],
        "ConType": 6,
        "Date": "30.03.2022 08:28",
        "Detail": "https://light.dsbcontrol.de/DSBlightWebsite/Data/someUUID/someUUID/esis.html",
        "Id": "someUUID_175",
        "Index": 175,
        "Preview": "someUUID/someUUID/preview.png",
        "Prio": 0,
        "Tags": "",
        "Title": "esis",
      },
    ],
    "ConType": 2,
    "Date": "30.03.2022 08:28",
    "Detail": "",
    "Id": "someUUID",
    "Index": 0,
    "Preview": "",
    "Prio": 0,
    "Tags": "",
    "Title": "Vetretungen_mobil - esis",
  },
]
```

I haven't figured out when exactly the error occurs (sometimes the correct data is sent on the second request, sometimes not).

![image](https://user-images.githubusercontent.com/52716424/160807452-9d7417eb-03b6-4c7b-9796-b05f912852bb.png)

**Comment by jukodev** [comment]
funkt

**Comment by jukodev** [comment]
![hery](https://user-images.githubusercontent.com/75746485/161403877-c51cc04f-6d14-416d-b04f-ef12d223a092.jpg)

**Comment by jukodev** [comment]
![kleinfeld15](https://user-images.githubusercontent.com/75746485/161403886-c69667b8-f9f4-4972-9077-9bfa0babc9c5.gif)
